import React, { useEffect } from 'react';
import { Shield, Target, Eye, Sparkles } from 'lucide-react';

function About() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const pillars = [
    {
      icon: <Target size={24} />,
      title: 'Mission',
      text: 'Build software that is practical, secure, and valuable for businesses that need reliable digital systems.',
    },
    {
      icon: <Eye size={24} />,
      title: 'Vision',
      text: 'Become a trusted African software company delivering marketplace products, portals, and automation tools.',
    },
    {
      icon: <Shield size={24} />,
      title: 'Values',
      text: 'Quality, accountability, clean delivery, and long-term support for every client engagement.',
    },
  ];

  const strengths = [
    'Product strategy and discovery',
    'React and FastAPI delivery',
    'Marketplace and licensing systems',
    'Business portal access control',
    'Production deployment and support',
    'Secure file handling and payments',
  ];

  return (
    <div className="page-shell">
      <section className="page-hero" style={{ minHeight: '420px' }}>
        <div className="hero-overlay" style={{ background: 'linear-gradient(135deg, rgba(11,60,93,0.92), rgba(17,17,17,0.9))' }}>
          <div className="container">
            <div className="hero-content">
              <div className="hero-text" data-aos="fade-right">
                <h1 style={{ fontSize: 'clamp(2.3rem, 5vw, 4rem)' }}>About Akagera Inc</h1>
                <p style={{ maxWidth: '760px' }}>
                  Akagera Inc is a software development company focused on building modern digital solutions for businesses, customers, and internal teams.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="section-padding">
        <div className="container">
          <div className="section-title" data-aos="fade-up">
            <h2>Who We Are</h2>
            <p>We design, build, and support software systems that help organizations work faster and look more professional online.</p>
          </div>

          <div className="page-grid-three">
            {pillars.map((pillar) => (
              <div key={pillar.title} className="surface-card" style={{ padding: '30px' }}>
                <div style={{ width: '48px', height: '48px', borderRadius: '14px', display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(11,60,93,0.1)', color: 'var(--primary-blue)', marginBottom: '16px' }}>
                  {pillar.icon}
                </div>
                <h3 style={{ color: 'var(--primary-blue)' }}>{pillar.title}</h3>
                <p style={{ color: 'var(--dark-gray)', marginBottom: 0 }}>{pillar.text}</p>
              </div>
            ))}
          </div>

          <div className="page-grid-two" style={{ marginTop: '34px' }}>
            <div className="dark-surface surface-card" style={{ padding: '34px' }}>
              <h3 style={{ color: 'white', marginBottom: '18px' }}>What We Deliver</h3>
              <div style={{ display: 'grid', gap: '12px' }}>
                {strengths.map((item) => (
                  <div key={item} style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                    <Sparkles size={18} />
                    <span>{item}</span>
                  </div>
                ))}
              </div>
            </div>

            <div className="surface-card" style={{ padding: '34px' }}>
              <h3 style={{ color: 'var(--primary-blue)' }}>Production Ready Mindset</h3>
              <p style={{ color: 'var(--dark-gray)' }}>
                The website is structured to support public marketing pages, software products, business portals, admin workflows, and secure payments.
              </p>
              <div style={{ display: 'grid', gap: '10px', marginTop: '18px' }}>
                <div className="badge">JWT auth ready</div>
                <div className="badge">Contact submissions saved</div>
                <div className="badge">Business tokens generated by admin</div>
                <div className="badge">Marketplace and licensing support</div>
              </div>
            </div>
          </div>

          <div className="surface-card" style={{ marginTop: '34px', padding: '34px' }}>
            <h3 style={{ color: 'var(--primary-blue)', marginBottom: '16px' }}>Team and Approach</h3>
            <p style={{ color: 'var(--dark-gray)', marginBottom: 0 }}>
              The delivery approach combines product planning, UI design, backend engineering, and deployment discipline so the website can grow with the company.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
}

export default About;
